require: rubocop-performance

Rails:
    Enabled: true

Metrics/LineLength:
    Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'config/**/*'
