default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: coredump_water_sensor_api_development

test:
  <<: *default
  database: coredump_water_sensor_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>